import { jsPDF } from "jspdf";
import { PreparednessPlanResponse } from "@/types/planner";

export function downloadPlanPDF(plan: PreparednessPlanResponse) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = 210;
  const pageHeight = 297;
  const margin = 20;
  const contentWidth = pageWidth - margin * 2; // 170mm
  let yPos = margin;
  let pageNum = 1;

  // Color Palette Definitions
  const colorPrimary = [15, 23, 42]; // Slate 900
  const colorSecondary = [71, 85, 105]; // Slate 600
  const colorAccent = [6, 182, 212]; // Cyan 500
  const colorText = [51, 65, 85]; // Slate 700

  // Helper: Draw page header and footer
  const drawPageDecorations = (pdfDoc: jsPDF) => {
    // Header line
    pdfDoc.setDrawColor(226, 232, 240); // Slate 200
    pdfDoc.setLineWidth(0.3);
    pdfDoc.line(margin, 12, pageWidth - margin, 12);

    // Header title
    pdfDoc.setFont("helvetica", "bold");
    pdfDoc.setFontSize(8);
    pdfDoc.setTextColor(148, 163, 184); // Slate 400
    pdfDoc.text("MONSOONMATE AI CIVIL READY COMMAND", margin, 9);

    // Footer line
    pdfDoc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    // Footer copyright
    pdfDoc.setFont("helvetica", "italic");
    pdfDoc.setFontSize(8);
    pdfDoc.text("Generated by MonsoonMate AI — Public Safety Advisory", margin, pageHeight - 10);
    pdfDoc.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 10);
  };

  const checkPageBreak = (neededHeight: number) => {
    if (yPos + neededHeight > pageHeight - margin - 15) {
      doc.addPage();
      pageNum += 1;
      yPos = margin + 10; // Start lower to clear the header
      drawPageDecorations(doc);
    }
  };

  // 1. Initial Page Setup
  drawPageDecorations(doc);

  // 2. Document Title Block
  yPos = 25;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text("PERSONAL PREPAREDNESS PLAN", margin, yPos);
  
  yPos += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(colorSecondary[0], colorSecondary[1], colorSecondary[2]);
  doc.text(`Target Locale Preferred Language: ${plan.language.toUpperCase()}`, margin, yPos);

  yPos += 5;
  doc.setDrawColor(203, 213, 225); // Slate 300
  doc.setLineWidth(0.6);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 10;

  // 3. Section: Risk Evaluation
  checkPageBreak(30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("1. METEOROLOGICAL THREAT EVALUATION", margin, yPos);
  
  yPos += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text(`RISK LEVEL STATE: ${plan.riskLevel.toUpperCase()}`, margin, yPos);
  
  yPos += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(colorText[0], colorText[1], colorText[2]);
  const splitRiskSummary = doc.splitTextToSize(plan.riskSummary, contentWidth);
  doc.text(splitRiskSummary, margin, yPos);
  yPos += (splitRiskSummary.length * 4.5) + 8;

  // 4. Section: Today's Priority Actions
  const priorityHeaderHeight = 12;
  const estimatedPriorityHeight = priorityHeaderHeight + (plan.preparednessPlan.today.length * 8);
  checkPageBreak(Math.min(estimatedPriorityHeight, 60)); // ensure at least header + some items fit
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("2. TODAY'S PRIORITY PROCEDURES", margin, yPos);
  yPos += 7;

  plan.preparednessPlan.today.forEach((action) => {
    const wrappedAction = doc.splitTextToSize(`[ ]  ${action}`, contentWidth - 5);
    checkPageBreak(wrappedAction.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(colorText[0], colorText[1], colorText[2]);
    doc.text(wrappedAction, margin + 2, yPos);
    yPos += (wrappedAction.length * 5) + 1.5;
  });
  yPos += 6;

  // 5. Section: Timeline Protocols
  checkPageBreak(30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("3. READINESS TIMELINE PROTOCOLS", margin, yPos);
  yPos += 7;

  // Timeline: Tomorrow
  checkPageBreak(15);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text("Phase A: Pre-Storm Preparation (Tomorrow)", margin, yPos);
  yPos += 5.5;
  
  plan.preparednessPlan.tomorrow.forEach((item) => {
    const wrappedItem = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
    checkPageBreak(wrappedItem.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(colorText[0], colorText[1], colorText[2]);
    doc.text(wrappedItem, margin + 2, yPos);
    yPos += (wrappedItem.length * 5) + 1;
  });
  yPos += 4;

  // Timeline: During Rain
  checkPageBreak(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text("Phase B: In-Storm Protocols (During Rain)", margin, yPos);
  yPos += 5.5;
  
  plan.preparednessPlan.duringRain.forEach((item) => {
    const wrappedItem = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
    checkPageBreak(wrappedItem.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(colorText[0], colorText[1], colorText[2]);
    doc.text(wrappedItem, margin + 2, yPos);
    yPos += (wrappedItem.length * 5) + 1;
  });
  yPos += 4;

  // Timeline: After Rain
  checkPageBreak(20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text("Phase C: Recovery Protocols (After Rain)", margin, yPos);
  yPos += 5.5;
  
  plan.preparednessPlan.afterRain.forEach((item) => {
    const wrappedItem = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
    checkPageBreak(wrappedItem.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(colorText[0], colorText[1], colorText[2]);
    doc.text(wrappedItem, margin + 2, yPos);
    yPos += (wrappedItem.length * 5) + 1;
  });
  yPos += 8;

  // 6. Section: Travel Advisory
  checkPageBreak(35);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("4. TRANSIT AND TRAVEL ADVISORY", margin, yPos);
  
  yPos += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text(`TRANSIT STATUS: ${plan.travelAdvisory.status.toUpperCase()}`, margin, yPos);
  
  yPos += 5;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(colorText[0], colorText[1], colorText[2]);
  const splitAdvisory = doc.splitTextToSize(plan.travelAdvisory.recommendation, contentWidth);
  doc.text(splitAdvisory, margin, yPos);
  yPos += (splitAdvisory.length * 4.5) + 5;

  // Travel lists
  checkPageBreak(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.text("Avoid Situations:", margin, yPos);
  yPos += 5;
  plan.travelAdvisory.avoid.forEach((item) => {
    const wrapped = doc.splitTextToSize(`- ${item}`, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 1;
  });
  yPos += 4;

  checkPageBreak(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.text("Safe Options/Routes:", margin, yPos);
  yPos += 5;
  plan.travelAdvisory.safeOptions.forEach((item) => {
    const wrapped = doc.splitTextToSize(`- ${item}`, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 1;
  });
  yPos += 8;

  // 7. Section: Emergency Kit & Checklist
  checkPageBreak(40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("5. CRITICAL PROVISIONS AND CHECKLISTS", margin, yPos);
  yPos += 7;

  // Kit Items
  checkPageBreak(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorPrimary[0], colorPrimary[1], colorPrimary[2]);
  doc.text("Emergency Supply Grab-Bag Items:", margin, yPos);
  yPos += 5.5;
  
  plan.emergencyKit.forEach((item) => {
    const wrapped = doc.splitTextToSize(`[ ]  ${item}`, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 1;
  });
  yPos += 4;

  // Checklist Items
  checkPageBreak(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Profile-Based Safety Checklist:", margin, yPos);
  yPos += 5.5;
  
  plan.emergencyChecklist.forEach((item) => {
    const wrapped = doc.splitTextToSize(`[ ]  ${item}`, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 1;
  });
  yPos += 8;

  // 8. Section: Community Recommendations
  checkPageBreak(30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("6. COMMUNITY SAFETY RECOMMENDATIONS", margin, yPos);
  yPos += 7;

  plan.communityRecommendations.forEach((item) => {
    const wrapped = doc.splitTextToSize(`• ${item}`, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(colorText[0], colorText[1], colorText[2]);
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 1;
  });
  yPos += 8;

  // 9. Section: Emergency Contacts
  checkPageBreak(35);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("7. EMERGENCY SUPPORT TELEPHONY", margin, yPos);
  yPos += 7;

  plan.emergencyContacts.forEach((contact) => {
    const contactText = `${contact.name} - ${contact.reason}`;
    const wrapped = doc.splitTextToSize(contactText, contentWidth - 5);
    checkPageBreak(wrapped.length * 5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.text(wrapped, margin + 2, yPos);
    yPos += (wrapped.length * 5) + 2;
  });
  yPos += 8;

  // 10. Final AI Message Statement
  checkPageBreak(30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(colorAccent[0], colorAccent[1], colorAccent[2]);
  doc.text("CIVIL OFFICER ADVISORY", margin, yPos);
  yPos += 5.5;

  doc.setFont("helvetica", "oblique");
  doc.setFontSize(9.5);
  doc.setTextColor(colorText[0], colorText[1], colorText[2]);
  const splitFinalMsg = doc.splitTextToSize(`"${plan.finalMessage}"`, contentWidth);
  doc.text(splitFinalMsg, margin, yPos);

  // 11. Save PDF locally
  const locationCity = plan.riskSummary.toLowerCase().includes("mumbai") ? "Mumbai" : "MonsoonMate";
  doc.save(`${locationCity}_Preparedness_Plan.pdf`);
}
